import{createClient}from"https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const env=(k:string)=>{const v=Deno.env.get(k);if(!v)throw new Error(`${k} required`);return v};
const clean=(v:FormDataEntryValue|null)=>String(v||"").trim();
const lower=(v:unknown)=>String(v||"").trim().toLowerCase();
const fileSafe=(name:string)=>name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_").replace(/[^a-zA-Z0-9._()-]/g,"").slice(0,140)||"archivo";
const getIp=(req:Request)=>req.headers.get("cf-connecting-ip")||req.headers.get("x-forwarded-for")||req.headers.get("x-real-ip")||"unknown";
const allowedExt=new Set(["jpg","jpeg","png","webp","pdf","xml","xls","xlsx","csv","txt","zip"]);
const allowedMime=new Set(["image/jpeg","image/png","image/webp","application/pdf","text/xml","application/xml","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/csv","text/plain","application/zip","application/x-zip-compressed"]);
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Método no permitido"},405);try{
const sb=createClient(env("SUPABASE_URL"),env("SUPABASE_SERVICE_ROLE_KEY")),form=await req.formData(),folio=clean(form.get("folio")),token=clean(form.get("token")),texto=clean(form.get("texto")),ip=getIp(req),user_agent=req.headers.get("user-agent")||"",now=new Date().toISOString();
if(!folio||!token)return json({error:"Faltan datos"},400);
const{data:t,error}=await sb.from("tickets").select("id,cliente_id,folio,estado,timeline_publica,adjuntos,evidencia_count,token_publico,token_publico_expira").eq("folio",folio).eq("token_publico",token).maybeSingle();
if(error)return json({error:error.message},500);if(!t)return json({error:"No encontrado"},404);
if(t.token_publico_expira&&new Date(String(t.token_publico_expira)).getTime()<Date.now())return json({error:"Enlace expirado"},410);
if(["cerrado"].includes(lower(t.estado)))return json({error:"El ticket está cerrado"},409);
const files=[...form.entries()].filter(([k])=>k==="files").map(([,v])=>v).filter(v=>v instanceof File) as File[];
if(!texto&&!files.length)return json({error:"Agrega un mensaje o al menos un archivo"},400);
if(files.length>10)return json({error:"Máximo 10 archivos"},400);
if(texto.length>3000)return json({error:"El mensaje es demasiado largo"},400);
let totalBytes=0;for(const file of files){const safe=fileSafe(file.name),ext=(safe.split(".").pop()||"").toLowerCase(),mime=(file.type||"").toLowerCase(),size=Number(file.size||0);totalBytes+=size;if(!allowedExt.has(ext))return json({error:`Tipo no permitido: ${safe}`},400);if(mime&&!allowedMime.has(mime))return json({error:`MIME no permitido: ${safe}`},400);if(size<=0)return json({error:`Archivo vacío: ${safe}`},400);if(size>20*1024*1024)return json({error:`Archivo demasiado grande: ${safe}`},400);if(totalBytes>60*1024*1024)return json({error:"El total de archivos excede el máximo permitido"},400)}
const{data:lastPublic,error:lastErr}=await sb.from("ticket_eventos").select("autor_tipo,created_at").eq("ticket_id",t.id).eq("visibilidad","publica").in("autor_tipo",["cliente","soporte"]).order("created_at",{ascending:false}).limit(2);
if(lastErr)return json({error:lastErr.message},500);
const lp=Array.isArray(lastPublic)?lastPublic:[];if(lp.length>=2&&lower(lp[0]?.autor_tipo)==="cliente"&&lower(lp[1]?.autor_tipo)==="cliente")return json({error:"Ya envió 2 mensajes seguidos. Espere a que soporte responda."},409);
if(lower(t.estado)==="resuelto"){const ev0=await sb.from("ticket_eventos").insert({ticket_id:t.id,autor_tipo:"sistema",visibilidad:"publica",kind:"estado",texto:"El caso fue reabierto porque el cliente envió una nueva respuesta desde el portal.",meta:{canal:"portal",folio,estado_anterior:t.estado,estado_nuevo:"en_proceso"}});if(ev0.error)return json({error:ev0.error.message},500)}
if(texto){const ev=await sb.from("ticket_eventos").insert({ticket_id:t.id,autor_tipo:"cliente",visibilidad:"publica",kind:"mensaje",texto,meta:{canal:"portal",folio}});if(ev.error)return json({error:ev.error.message},500)}
const nuevosAdjuntos:Array<Record<string,unknown>>=[],erroresAdjuntos:Array<Record<string,unknown>>=[];
for(const file of files){const safe=fileSafe(file.name),mime=(file.type||"").toLowerCase(),path=`${t.id}/${Date.now()}_${crypto.randomUUID()}_${safe}`;try{const bytes=new Uint8Array(await file.arrayBuffer()),up=await sb.storage.from("soporte_adjuntos").upload(path,bytes,{contentType:mime||"application/octet-stream",upsert:false});if(up.error)throw new Error(`Error subiendo ${safe}: ${up.error.message}`);const archNew=await sb.from("archivos_ticket").insert({ticket_id:t.id,origen:"portal",visibilidad:"publica",nombre_archivo:file.name,storage_path:path,url_firma:null,mime_type:file.type||null,tamano_bytes:file.size,meta:{canal:"portal",folio}});if(archNew.error)throw new Error(`Error guardando archivo canónico ${safe}: ${archNew.error.message}`);const archLegacy=await sb.from("ticket_archivos").insert({ticket_id:t.id,nombre_archivo:file.name,url_archivo:path,mime_type:file.type||null,tamano_bytes:file.size});if(archLegacy.error)console.error("LEGACY_TICKET_ARCHIVOS_ERROR",archLegacy.error.message);nuevosAdjuntos.push({nombre:file.name,tipo:file.type||null,peso:file.size,storage_path:path,url:null,origen:"portal",fecha:now})}catch(e){console.error("PORTAL_FILE_SOFT_FAIL",safe,e);erroresAdjuntos.push({nombre:file.name,error:e instanceof Error?e.message:String(e),peso:file.size||0,tipo:file.type||null})}}
if(erroresAdjuntos.length){await sb.from("ticket_eventos").insert({ticket_id:t.id,autor_tipo:"sistema",visibilidad:"interna",kind:"archivo",texto:`No se pudieron procesar ${erroresAdjuntos.length} archivo(s) enviados desde el portal.`,meta:{errores:erroresAdjuntos,canal:"portal",folio}});if(!nuevosAdjuntos.length&&!texto)return json({error:"No se pudieron procesar los archivos adjuntos",errores:erroresAdjuntos},500)}
if(nuevosAdjuntos.length){const evFile=await sb.from("ticket_eventos").insert({ticket_id:t.id,autor_tipo:"cliente",visibilidad:"publica",kind:"archivo",texto:`El cliente adjuntó ${nuevosAdjuntos.length} archivo(s).`,meta:{adjuntos:nuevosAdjuntos,archivos_count:nuevosAdjuntos.length,canal:"portal",folio}});if(evFile.error)return json({error:evFile.error.message},500)}
const timelineActual=Array.isArray(t.timeline_publica)?t.timeline_publica:[],adjuntosActual=Array.isArray(t.adjuntos)?t.adjuntos:[],reabre=lower(t.estado)==="resuelto",nuevosEventosCompat=[...(reabre?[{kind:"estado",autor:"sistema",titulo:"Caso reabierto",texto:"El cliente respondió después de marcar el caso como resuelto.",fecha:now}]:[]),...(texto?[{kind:"mensaje",autor:"cliente",titulo:"Cliente respondió",texto,fecha:now}]:[]),...(nuevosAdjuntos.length?[{kind:"archivo",autor:"cliente",titulo:"Cliente adjuntó archivos",texto:`El cliente adjuntó ${nuevosAdjuntos.length} archivo(s).`,fecha:now,adjuntos:nuevosAdjuntos}]:[])],nuevoEstado="en_proceso";
const upTicket=await sb.from("tickets").update({estado:nuevoEstado,fecha_actualizacion:now,timeline_publica:[...timelineActual,...nuevosEventosCompat],adjuntos:[...adjuntosActual,...nuevosAdjuntos],evidencia_count:Number(t.evidencia_count||0)+nuevosAdjuntos.length}).eq("id",t.id);
if(upTicket.error)return json({error:upTicket.error.message},500);
try{await sb.from("ticket_portal_logs").insert({ticket_id:t.id,folio,evento:"reply",ip,user_agent,detalle:{texto:!!texto,files:nuevosAdjuntos.length,errores:erroresAdjuntos.length}})}catch{}
try{await sb.from("bitacora").insert({accion:"portal_respondio",cliente_id:t.cliente_id||null,detalle:{ticket_id:t.id,folio,texto:!!texto,files:nuevosAdjuntos.length,errores:erroresAdjuntos.length},visibilidad:"interna",tipo:"nota_interna"})}catch{}
return json({ok:true,ticket_id:t.id,folio,estado:nuevoEstado,files:nuevosAdjuntos.length,errores:erroresAdjuntos.length,responded:true},200);
}catch(e){return json({error:e instanceof Error?e.message:"Error"},500)}});