const V="tc-v1.2.4-whatsapp-header-05d",S=`static-${V}`,P=`pages-${V}`,A=["./","./index.html","./dashboard.html","./tickets.html","./ticket.html","./clientes.html","./cliente.html","./consolidacion-clientes.html","./alta-cliente.html","./soporte.html","./estado.html","./global.css","./global.js?v=frontend-stabilization-03b","./dashboard.css?v=whatsapp-header-05","./dashboard.js?v=whatsapp-header-05","./tickets.css?v=whatsapp-header-05","./tickets.js?v=whatsapp-header-05","./ticket.css?v=whatsapp-header-05","./ticket.js?v=whatsapp-header-05","./ticket-composer-polish.js","./shared/nav-interna.js?v=frontend-stabilization-03b","./config-loader.js","./theme.js","./soporte.css?v=whatsapp-consent-05","./soporte.js?v=whatsapp-consent-05","./estado.js?v=whatsapp-status-05b","./estado.css?v=whatsapp-status-05c","../favicon.ico","../favicon-16x16.png","../favicon-32x32.png","../apple-touch-icon.png","../site.webmanifest"];
self.addEventListener("install",e=>e.waitUntil((async()=>{const c=await caches.open(S);await Promise.all(A.map(async u=>{try{await c.add(new Request(u,{cache:"reload"}))}catch(err){console.warn("SW_SKIP",u,err)}}));await self.skipWaiting()})()));
self.addEventListener("activate",e=>e.waitUntil((async()=>{const ks=await caches.keys();await Promise.all(ks.filter(k=>![S,P].includes(k)).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener("fetch",e=>{const r=e.request,u=new URL(r.url);if(r.method!=="GET")return;if(u.origin!==location.origin)return;if(r.headers.has("authorization")||/\/(?:auth|rest|functions|storage)\/v1\//.test(u.pathname))return;
if(r.mode==="navigate")return e.respondWith((async()=>{try{const n=await fetch(r,{cache:"no-store"});if(n&&n.ok)(await caches.open(P)).put(r,n.clone());return n}catch{const c=await caches.open(P);return await c.match(r)||await c.match("./estado.html")||await c.match("./soporte.html")||await c.match("./dashboard.html")||await c.match("./index.html")||new Response("Sin conexión",{status:503,headers:{"Content-Type":"text/plain;charset=UTF-8"}})}})());
/* Assets: stale-while-revalidate. La respuesta caché es inmediata y la red
   refresca la misma versión; Auth/API quedan fuera por origen y método. */
e.respondWith((async()=>{const c=await caches.open(S),m=await c.match(r);const fresh=fetch(r,{cache:"no-store"}).then(n=>{if(n&&n.ok)c.put(r,n.clone());return n}).catch(()=>null);return m||await fresh||new Response("",{status:504})})());
});
