-- Ticket Core staging baseline 0009.
-- Preconditions: identity, clients and tickets exist.
-- Rollback: IRREVERSIBLE_WITHOUT_BACKUP once audit/idempotency data exists.
begin;

create table public.bitacora (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  actor_id uuid references public.perfiles(id) on delete set null,
  actor_tipo text not null default 'sistema' check (actor_tipo in ('anon', 'cliente', 'soporte', 'admin', 'sistema', 'service_role')),
  accion text not null,
  entidad_tipo text not null default 'sistema',
  entidad_id uuid,
  resultado text not null default 'ok' check (resultado in ('ok', 'rechazado', 'error', 'parcial')),
  resumen text,
  detalle jsonb not null default '{}'::jsonb,
  request_id uuid,
  -- Compatibility columns for the eight active Edge Functions. All timestamps
  -- remain timestamptz; these are retired only after consumers migrate.
  usuario_id uuid references public.perfiles(id) on delete set null,
  cliente_id uuid references public.clientes(id) on delete set null,
  fecha timestamptz generated always as (created_at) stored,
  visibilidad text not null default 'interna' check (visibilidad = 'interna'),
  tipo text not null default 'nota_interna' check (tipo = 'nota_interna'),
  check (app_private.audit_detail_is_safe(detalle)),
  check (resumen is null or char_length(resumen) <= 500)
);

comment on table public.bitacora is
  'Canonical audit log. Never store tokens, signed URLs, full request payloads, secrets or unnecessary PII.';

create table public.rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null,
  key_hash text not null check (key_hash ~ '^[a-f0-9]{64}$'),
  created_at timestamptz not null default now(),
  check (char_length(scope) between 1 and 80)
);

create table public.edge_idempotency (
  idempotency_key text primary key,
  action text not null check (
    action in (
      'crear_solicitud', 'responder_ticket', 'enviar_adjunto', 'escalar_administracion',
      'asignar_ticket', 'cerrar_ticket', 'consolidar_cliente',
      'ticket-internal-reply', 'crear_ticket_interno', 'crear_cliente',
      'respuesta_publica_ticket', 'support_submit_secure'
    )
    or action ~ '^ticket-escalar-admin:(chat_forwarded_to_admin|message_forwarded_to_admin|file_forwarded_to_admin|marcar_revisado)$'
  ),
  resource_id uuid,
  request_hash text not null check (request_hash ~ '^[a-f0-9]{64}$'),
  status text not null default 'processing' check (status in ('processing', 'completed', 'failed')),
  response jsonb,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  check (char_length(idempotency_key) between 16 and 200),
  check (response is null or app_private.audit_detail_is_safe(response)),
  check (expires_at > created_at)
);

commit;
